# Generated by Django 2.0.4 on 2018-05-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=6)),
                ('old_price', models.CharField(max_length=6)),
                ('slug', models.CharField(max_length=255)),
                ('imgage_id', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
