# Generated by Django 2.0.4 on 2018-05-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20180503_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField()),
                ('list_order', models.IntegerField()),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
